<p>Création de post</p>
<form method="GET" action="">
    <label for="title">Titre</label>
    <input type="text" name="title" id="title"/>
    <label for="categorie">Categorie</label>
    <input type="text" name="categorie" id="categorie"/>
    <label for="content">Contenu</label>
    <input type="text" name="content" id="content"/>
    <label for="author">Auteur</label>
    <input type="text" name="author" id="author"/>
    <input type="submit" value="Submit"/>
</form>