<?php
/*

_ admin-footer.phtml
Votre <footer> contiendra une <nav>
qui permet d'accéder à vos pages de liste des posts, 
de listes de catégories et de déconnexion.

*/
?>

<nav id="nav-footer-admin">
    <ul>
        <li><a href="index.php?route=admin-posts">Liste des posts</a></li>
        <li><a href="index.php?route=admin-categories">Listes des catégories de posts</a></li>
        <li><a href="index.php?route=logout">Déconnexion</a></li>
    </ul>
</nav>