<form method="POST" action="index.php">
    <label for="firstName">First name</label>
    <input type="text" name="firstName" id="firstName"/>
    <label for="lastName">Last name</label>
    <input type="text" name="lastName" id="lastName"/>
    <label for="email">Email</label>
    <input type="email" name="email" id="email"/>
    <label for="password">Password</label>
    <input type="password" name="password" id="password" autocomplete="new-password"/>
    <label for="confirmPassword">Confirm Password</label>
    <input type="password" name="confirmPassword" id="confirmPassword" autocomplete="new-password"/>
    <input type="hidden" name="formName"/>
    <input type="submit" value="Submit"/>
</form>